let strings = {
	"en-US": {
		"noVialsSet": "I need to know how many vials there are.",
		"moreEmptyVials": "There cannot be the same amount or more empty vials than there are vials.",
		"noMemory": "I ran out of memory looking for a solution, uncover more colors and try again.",
		"noSolution": "No solution found, check your colors and try again.",
		"tooManySolutions": "Too many possible solutions, I will probably crash your device trying to find a solution.",
		"drStrange": "There are %% possible solutions and the processing to determine them happens on your device.  Your device may become unresponsive for some time, or even freeze, requiring you to restart it.%%As far as I know there is no harmful permanent damage that can be done to your device.%%Do you wish to continue?",
		"resetColors": "Are you sure, you will lose any colors currently set?",
		"progress": "Attempting solution %% of %%",

		"colorSegments": "Color<br />Segments",
		"totalVials": "Total<br />Vials",
		"emptyVials": "Empty<br />Vials",

		"modalTitle": "WAIT!",
		"modalText": "Are you sure you want to complete this action?",
		"yesButton": "Ok",
		"cancel": "Cancel",
		"continueButton": "Resume",
		"sorry": "SORRY",
		"error": "ERROR",
		"about": "ABOUT",
		"howToUse": "HOW TO USE",
		"hotToUseTxt": "This tool will analyze your progress in the water sort style games and attempt to give you a step-by-step solution, there are 3 steps:",
		"config": "CONFIGURATION",
		"configTxt": "Set the vials equivalent to what appears in your game: select the segments for how many color sections appear in each vial, the total number of vials (including empty ones), and finally the number of empty vials.",
		"colorsTxt": "Click each segment and a popup will appear to choose a color for that segment.  If you select the wrong color you can reselect it, or you can delete the color.",
		"solutionTxt": "If you dont know all of the colors it will attempt to solve it for you<sup><strong>&dagger;</strong></sup>, keep in mind that this is only a guess and not a guaranteed solution.  If you know all of the colors, and there is a valid solution, it will present a solution you can step back and forth through to follow along to solve the puzzle (if you are using a computer you can also use the left/right arrow keys).",
		"footnoteTxt": "<strong>&dagger;</strong> <em>because the processing is done on your device it will only attempt to solve 7 unknown colors or less.<br />For reference calculating the movesets of each solution for 7 unknown colors has about 277,200 moves to see if there is a solution, this took my computer around 5 minutes. In the future I would like to optimize my code and the project and I will revisit the maximum attempts depending on optimization.</em>",
		"cookies": "COOKIES",
		"cookieTxt": "The only cookie in use is Google Analytics to monitor usage and failures in my code. I am not collecting any personal data, and as you can see there are no ads.  <a href=\"https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage\" target=\"_new\">LocalStorage</a> is used to store your language preference and your consent to this notice so it doesnt open every time you come to the page.",
		"attrib": "CONTENT/CODE COPYRIGHTS",
		"attribTxt": "<ul><li>Ruslan Kurdyumov - for his base starting point <a href=\"https://github.com/rkurdyumov/water_sort_solver\" target=\"_new\">water_sort_solver</a></li><li>Michael P. Cohen - for the <a href=\"https://www.freakflagsprite.com/\" target=\"_new\">images</a> used in language selection.</li><li><a href=\"https://fontawesome.com/\" target=\"_new\">FontAwesome</a> - for the icons used in this page</li></ul>",
		"acceptButton": "Accept and Close",

		"restoreProgress": "It looks like you made a previous attempt, would you like to restore it?",

		"colors": "COLORS",
		"reset": "RESET",
		"attempt": "ATTEMPT",
		"solution": "SOLUTION",
		"back": "BACK",
		"next": "NEXT"
	},
	"it-IT": {
		"noVialsSet": "Ho bisogno di sapere quante fiale ci sono.",
		"moreEmptyVials": "Non possono esserci fiale vuote in numero uguale o superiore alle fiale presenti.",
		"noMemory": "Ho esaurito la memoria cercando una soluzione, ho scoperto altri colori e ho riprovato.",
		"noSolution": "Nessuna soluzione trovata, controlla i colori e riprova.",
		"tooManySolutions": "Troppe soluzioni possibili, probabilmente farò crashare il tuo dispositivo nel tentativo di trovare una soluzione.",
		"drStrange": "Esistono %% soluzioni possibili e l'elaborazione per determinarle viene eseguita sul tuo dispositivo. Il tuo dispositivo potrebbe non rispondere per un po' di tempo o addirittura bloccarsi, richiedendoti di riavviarlo.%%Per quanto ne so, non è possibile arrecare danni permanenti dannosi al tuo dispositivo.%%Vuoi continuare?",
		"resetColors": "Sei sicuro che perderai tutti i colori attualmente impostati?",
		"progress": "Tentativo di soluzione %% di %%",

		"colorSegments": "Colore<br />Segmenti",
		"totalVials": "Totale<br />Fiale",
		"emptyVials": "Fiale<br />vuote",

		"modalTitle": "ATTESA!",
		"modalText": "Sei sicuro di voler completare questa azione?",
		"yesButton": "Si",
		"cancel": "Annulla",
		"continueButton": "Continuare",
		"sorry": "MI SCUSI",
		"error": "ERRORE",
		"about": "CIRCA",
		"howToUse": "COME USARE",
		"hotToUseTxt": "Questo strumento analizzerà i tuoi progressi nei giochi in stile ordinamento dell'acqua e tenterà di darti una soluzione passo dopo passo, ci sono 3 passaggi:",
		"config": "CONFIGURAZIONE",
		"configTxt": "Imposta le fiale in modo che corrispondano a quelle che appaiono nel tuo gioco: seleziona i segmenti per indicare quante sezioni colorate appaiono in ogni fiala, il numero totale di fiale (incluse quelle vuote) e, infine, il numero di fiale vuote.",
		"colorsTxt": "Fai clic su ogni segmento e apparirà un popup per scegliere un colore per quel segmento. Se selezioni il colore sbagliato, puoi riselezionarlo o puoi eliminare il colore.",
		"solutionTxt": "Se non conosci tutti i colori che tenterà di risolverlo per te<sup><strong>&dagger;</strong></sup>, tieni presente che questa è solo un'ipotesi e non una soluzione garantita. Se conosci tutti i colori e c'è una soluzione valida, ti presenterà una soluzione che puoi seguire avanti e indietro per risolvere il puzzle (se stai usando un computer, puoi anche usare i tasti freccia sinistra/destra).",
		"footnoteTxt": "<strong>&dagger;</strong> <em>poiché l'elaborazione viene eseguita sul tuo dispositivo, tenterà di risolvere solo 7 colori sconosciuti o meno.<br />Per riferimento, il calcolo dei set di mosse di ogni soluzione per 7 colori sconosciuti ha circa 277.200 mosse per vedere se c'è una soluzione, il mio computer ha impiegato circa 5 minuti. In futuro vorrei ottimizzare il mio codice e il progetto e riesaminerò i tentativi massimi a seconda dell'ottimizzazione.</em>",
		//"cookies": "COOKIES",
		"cookieTxt": "L'unico cookie in uso è Google Analytics per monitorare l'utilizzo e gli errori nel mio codice. Non raccolgo dati personali e, come puoi vedere, non ci sono annunci pubblicitari. <a href=\"https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage\" target=\"_new\">LocalStorage</a> viene utilizzato per memorizzare la tua preferenza di lingua e il tuo consenso a questa nota in modo che non si apra ogni volta che visiti la pagina.",
		"attrib": "COPYRIGHT SUI CONTENUTI/CODICI",
		"attribTxt": "<ul><li>Ruslan Kurdyumov - per il suo punto di partenza di base <a href=\"https://github.com/rkurdyumov/water_sort_solver\" target=\"_new\">water_sort_solver</a></li><li>Michael P. Cohen - per le <a href=\"https://www.freakflagsprite.com/\" target=\"_new\">immagini</a> utilizzate nella selezione della lingua.</li><li><a href=\"https://fontawesome.com/\" target=\"_new\">FontAwesome</a> - per le icone utilizzate in questa pagina</li></ul>",
		"acceptButton": "Accetta e chiudi",

		"restoreProgress": "Sembra che tu abbia fatto un tentativo precedente. Vuoi ripristinarlo?",

		"colors": "COLORI",
		"reset": "RESET",
		"attempt": "TENTATIVO",
		"solution": "SOLUZIONE",
		"back": "INDIETRO",
		"next": "PROSSIMO"
	},
	"es-ES": {
		"noVialsSet": "Necesito saber cuantos viales hay.",
		"moreEmptyVials": "No puede haber la misma cantidad o más viales vacíos que viales.",
		"noMemory": "Me quedé sin memoria buscando una solución, descubrir más colores y volver a intentarlo.",
		"noSolution": "No se encontró solución, verifique sus colores y vuelva a intentarlo.",
		"tooManySolutions": "Demasiadas soluciones posibles, probablemente bloquearé su dispositivo tratando de encontrar una solución.",
		"drStrange": "Hay %% posibles soluciones y el proceso para determinarlas se lleva a cabo en tu dispositivo. Es posible que tu dispositivo no responda durante un tiempo o incluso se congele, lo que requerirá que lo reinicies.%%Hasta donde sé, no se pueden producir daños permanentes perjudiciales en tu dispositivo.%%¿Deseas continuar?",
		"resetColors": "¿Estás seguro de que perderás los colores configurados actualmente?",
		"progress": "Intentando solución %% de %%",

		"colorSegments": "Segmentos<br />de color",
		"totalVials": "Total<br />de viales",
		"emptyVials": "Viales<br />vacíos",

		"modalTitle": "¡ESPERE!",
		"modalText": "¿Está seguro de que desea completar esta acción?",
		"yesButton": "Sí",
		"cancel": "Cancelar",
		"continueButton": "Continuar",
		"sorry": "PERDÓN",
		"error": "FALLO",
		"about": "ACERCA DE",
		"howToUse": "COMO USAR",
		"hotToUseTxt": "Esta herramienta analizará tu progreso en los juegos de estilo de clasificación de agua e intentará darte una solución paso a paso, hay 3 pasos:",
		"config": "CONFIGURACIÓN",
		"configTxt": "Establece los viales equivalentes a lo que aparece en tu juego: selecciona los segmentos para la cantidad de secciones de color que aparecen en cada vial, el número total de viales (incluidos los vacíos) y, finalmente, el número de viales vacíos.",
		"colorsTxt": "Haga clic en cada segmento y aparecerá una ventana emergente para elegir un color para ese segmento. Si selecciona el color incorrecto, puede volver a seleccionarlo o eliminar el color.",
		"solutionTxt": "Si no conoces todos los colores, intentará resolverlo por ti<sup><strong>&dagger;</strong></sup>, ten en cuenta que esto es solo una suposición y no una solución garantizada. Si conoces todos los colores y hay una solución válida, te presentará una solución que puedes recorrer de un lado a otro para seguirla y resolver el rompecabezas (si estás usando una computadora, también puedes usar las teclas de flecha izquierda/derecha).",
		"footnoteTxt": "<strong>&dagger;</strong> <em>Debido a que el procesamiento se realiza en su dispositivo, solo intentará resolver 7 colores desconocidos o menos.<br />Como referencia, calcular los conjuntos de movimientos de cada solución para 7 colores desconocidos tiene aproximadamente 277,200 movimientos para ver si hay una solución; esto le llevó a mi computadora alrededor de 5 minutos. En el futuro, me gustaría optimizar mi código y el proyecto y volveré a revisar los intentos máximos según la optimización.</em>",
		//"cookies": "COOKIES",
		"cookieTxt": "La única cookie que utilizo es la de Google Analytics para monitorizar el uso y los fallos en mi código. No recopilo ningún dato personal y, como puedes ver, no hay anuncios. <a href=\"https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage\" target=\"_new\">LocalStorage</a> se utiliza para almacenar tu preferencia de idioma y tu consentimiento a este aviso para que no se abra cada vez que accedas a la página.",
		"attrib": "CONTENIDO/CÓDIGO DERECHOS DE AUTOR",
		"attribTxt": "<ul><li>Ruslan Kurdyumov: por su punto de partida básico <a href=\"https://github.com/rkurdyumov/water_sort_solver\" target=\"_new\">water_sort_solver</a></li><li>Michael P. Cohen: por las <a href=\"https://www.freakflagsprite.com/\" target=\"_new\">imágenes</a> utilizadas en la selección del idioma.</li><li><a href=\"https://fontawesome.com/\" target=\"_new\">FontAwesome</a>: por los íconos utilizados en esta página</li></ul>",
		"acceptButton": "Aceptar y cerrar",

		"restoreProgress": "Parece que hiciste un intento anterior, ¿te gustaría restaurarlo?",

		"colors": "COLORES",
		"reset": "REINICIAR",
		"attempt": "INTENTAR",
		"solution": "SOLUCIÓN",
		"back": "ATRÁS",
		"next": "PRÓXIMO"
	},
	"de-DE": {
		"noVialsSet": "Ich muss wissen, wie viele Reagenzgläser gibt.",
		"moreEmptyVials": "Es kann nicht so viele oder mehr leere Reagenzgläser geben, wie Reagenzgläser zur Verfügung stehen.",
		"noMemory": "Bei der Suche nach einer Lösung ging mir der Speicher aus. Ich habe weitere Farben gefunden und es erneut versucht.",
		"noSolution": "Keine Lösung gefunden. Überprüfen Sie Ihre Farben und versuchen Sie es erneut.",
		"tooManySolutions": "Zu viele mögliche Lösungen. Wahrscheinlich werde ich Ihr Gerät beim Versuch, eine Lösung zu finden, zum Absturz bringen.",
		"drStrange": "Es gibt %% mögliche Lösungen und die Verarbeitung zu deren Ermittlung erfolgt auf Ihrem Gerät. Ihr Gerät reagiert möglicherweise für einige Zeit nicht oder friert sogar ein, sodass Sie es neu starten müssen.%%Soweit mir bekannt ist, kann Ihr Gerät nicht dauerhaft beschädigt werden.%%Möchten Sie fortfahren?",
		"resetColors": "Sind Sie sicher? Alle ihre aktuell eingestellten Farben werden zurück gesetzt.",
		"progress": "Lösungsversuch %% von %%",

		"colorSegments": "Farbsegmente",
		"totalVials": "Gesamtmenge<br />Reagenzgläser",
		"emptyVials": "Leere<br />Reagenzgläser",

		"modalTitle": "WARTEN!",
		"modalText": "Möchten Sie diese Aktion wirklich abschließen?",
		"yesButton": "Ja",
		"cancel": "Abbrechen",
		"continueButton": "Weitermachen",
		"sorry": "VERZEIHUNG",
		"error": "FEHLER",
		"about": "UM / ÜBER",
		"howToUse": "WIE MAN SIE BENUTZT",
		"hotToUseTxt": "Dieses Tool analysiert Ihren Fortschritt in den Wassersortierspielen und versucht, Ihnen eine Schritt-für-Schritt-Lösung zu bieten. Es besteht aus drei Schritten:",
		"config": "KONFIGURATION",
		"configTxt": "Stellen Sie die Reagenzgläser so ein, wie sie in Ihrem Spiel vorkommen: Wählen Sie die Segmente für die Anzahl der in jedem Reagenzglas vorkommenden Farbabschnitte, die Gesamtzahl der Reagenzgläser (einschließlich der leeren) und schließlich die Anzahl der leeren Reagenzgläser aus.",
		"colorsTxt": "Klicken Sie auf jedes Segment. Ein Popup wird angezeigt, in dem Sie eine Farbe für dieses Segment auswählen können. Wenn Sie die falsche Farbe auswählen, können Sie sie erneut auswählen oder die Farbe löschen.",
		"solutionTxt": "Wenn Sie nicht alle Farben kennen, wird versucht, das Rätsel für Sie zu lösen. <sup><strong>&dagger;</strong></sup> Beachten Sie, dass dies nur eine Vermutung und keine garantierte Lösung ist. Wenn Sie alle Farben kennen und es eine gültige Lösung gibt, wird eine Lösung angezeigt, in der Sie vor- und zurückblättern können, um das Rätsel zu lösen (wenn Sie einen Computer verwenden, können Sie auch die Pfeiltasten links/rechts verwenden).",
		"footnoteTxt": "<strong>&dagger;</strong> <em>Da die Verarbeitung auf Ihrem Gerät erfolgt, wird nur versucht, 7 unbekannte Farben oder weniger zu lösen.<br />Als Referenz: Die Berechnung der Movesets jeder Lösung für 7 unbekannte Farben hat ca 277.200 Züge, um zu sehen, ob es eine Lösung gibt, dafür hat mein Computer etwa 5 Minuten gebraucht. In Zukunft möchte ich meinen Code und das Projekt optimieren und werde die maximalen Versuche je nach Optimierung erneut prüfen.</em>",
		//"cookies": "COOKIES",
		"cookieTxt": "Das einzige verwendete Cookie ist Google Analytics, um die Nutzung und Fehler in meinem Code zu überwachen. Ich sammle keine persönlichen Daten und wie Sie sehen, gibt es keine Werbung. <a href=\"https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage\" target=\"_new\">LocalStorage</a> wird verwendet, um Ihre Sprachpräferenz und Ihre Zustimmung zu diesem Hinweis zu speichern, damit er nicht jedes Mal geöffnet wird, wenn Sie die Seite aufrufen.",
		"attrib": "URHEBERRECHTE FÜR INHALT/CODE",
		"attribTxt": "<ul><li>Ruslan Kurdyumov – für seinen Basis-Ausgangspunkt <a href=\"https://github.com/rkurdyumov/water_sort_solver\" target=\"_new\">water_sort_solver</a></li><li>Michael P. Cohen – für die <a href=\"https://www.freakflagsprite.com/\" target=\"_new\">Bilder</a>, die bei der Sprachauswahl verwendet werden.</li><li><a href=\"https://fontawesome.com/\" target=\"_new\">FontAwesome</a> – für die auf dieser Seite verwendeten Symbole</li></ul>",
		"acceptButton": "Akzeptieren und schließen",

		"restoreProgress": "Anscheinend haben Sie einen früheren Versuch unternommen. Möchten Sie ihn wiederherstellen?",

		"colors": "FARBEN",
		"reset": "ZURÜCKSETZEN",
		"attempt": "VERSUCHEN",
		"solution": "LÖSUNG",
		"back": "ZURÜCK",
		"next": "NÄCHSTE"
	},
	"ja-JP": {
		"noVialsSet": "バイアルが何本あるかを知る必要があります。",
		"moreEmptyVials": "空のバイアルの数がバイアルの総数と同じかそれ以上になることはできません。",
		"noMemory": "解決策を探してメモリが不足しました。さらに色を見つけて、もう一度試してください。",
		"noSolution": "解決策が見つかりません。色を確認してもう一度お試しください。",
		"tooManySolutions": "解決策が多すぎるため、解決策を見つけようとするとデバイスがクラッシュする可能性があります。",
		"drStrange": "%% の解決策が考えられますが、それらを決定する処理はデバイス上で行われます。デバイスがしばらく応答しなくなったり、フリーズしたりして、再起動が必要になる場合があります。%%私の知る限り、デバイスに永久的な損傷を与えることはありません。%%続行しますか?",
		"resetColors": "現在設定されている色はすべて失われますが、よろしいですか?",
		"progress": "ソリューションを試みています %% / ##",

		"colorSegments": "色のセグメント",
		"totalVials": "合計バイアル数",
		"emptyVials": "空の瓶",

		"modalTitle": "待つ!",
		"modalText": "この操作を完了してもよろしいですか?",
		"yesButton": "はい",
		"cancel": "中止",
		"continueButton": "続ける",
		"sorry": "ごめん",
		"error": "エラー",
		"about": "について",
		"howToUse": "使い方",
		"hotToUseTxt": "このツールは、ウォーター ソート スタイルのゲームの進行状況を分析し、段階的な解決策を提供します。次の 3 つのステップがあります。",
		"config": "構成",
		"configTxt": "ゲームに表示されるものと同等のバイアルを設定します。各バイアルに表示されるカラー セクションの数、バイアルの総数 (空のバイアルを含む)、最後に空のバイアルの数のセグメントを選択します。",
		"colorsTxt": "各セグメントをクリックすると、ポップアップが表示され、そのセグメントの色を選択します。間違った色を選択した場合は再選択することができ、色を削除することもできます。",
		"solutionTxt": "すべての色を知らない場合は、自動的に解決しようとします<sup><strong>&dagger;</strong></sup>。ただし、これは推測にすぎず、保証された解決法ではないことに注意してください。すべての色を知っていて、有効な解決法がある場合は、パズルを解くために実行できる解決法が表示されます (コンピューターを使用している場合は、左/右矢印キーを使用することもできます)。",
		"footnoteTxt": "<strong>&dagger;</strong> <em>処理はデバイス上で行われるため、7 色以下の未知の色のみを解決しようとします。<br />参考までに、7 色の未知の色について各ソリューションの移動セットを計算すると、ソリューションがあるかどうかを確認するのに約 277,200 の移動が必要になり、私のコンピューターではこれに約 5 分かかりました。今後はコードとプロジェクトを最適化し、最適化に応じて最大試行回数を再検討したいと思います。</em>",
		//"cookies": "COOKIES",
		"cookieTxt": "使用されている Cookie は、コードの使用状況と障害を監視する Google Analytics のみです。個人データを収集しているわけではなく、ご覧のとおり広告もありません。<a href=\"https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage\" target=\"_new\">LocalStorage</a> は、言語設定とこの通知への同意を保存するために使用されるため、このページにアクセスするたびにこの通知が開かれることはありません。",
		"attrib": "コンテンツ/コードの著作権",
		"attribTxt": "<ul><li>Ruslan Kurdyumov - ベースとなる出発点 <a href=\"https://github.com/rkurdyumov/water_sort_solver\" target=\"_new\">water_sort_solver</a></li><li>Michael P. Cohen - 言語の選択に使用される<a href=\"https://www.freakflagsprite.com/\" target=\"_new\">画像</a>について。</li><li><a href=\"https://fontawesome.com/\" target=\"_new\">FontAwesome</a> - このページで使用されているアイコン用</li></ul>",
		"acceptButton": "承諾して閉じる",

		"restoreProgress": "以前に試行が行われたようですが、復元しますか?",

		"colors": "カラーズ",
		"reset": "リセット",
		"attempt": "試み",
		"solution": "解決",
		"back": "戻る",
		"next": "次に"
	},
	"fr-FR": {
		"noVialsSet": "Je dois savoir combien il y a de flacons.",
		"moreEmptyVials": "Il ne peut pas y avoir la même quantité ou plus de flacons vides qu’il n’y a de flacons au total.",
		"noMemory": "J'ai manqué de mémoire en cherchant une solution, découvrez plus de couleurs et réessayez.",
		"noSolution": "Aucune solution trouvée, vérifiez vos couleurs et réessayez.",
		"tooManySolutions": "Il y a trop de solutions possibles, je vais probablement faire planter votre appareil en essayant de trouver une solution.",
		"drStrange": "Il existe %% solutions possibles et le traitement pour les déterminer se déroule sur votre appareil. Votre appareil peut cesser de répondre pendant un certain temps, voire se bloquer, vous obligeant à le redémarrer.%%Pour autant que je sache, aucun dommage permanent ne peut être causé à votre appareil.%%Souhaitez-vous continuer?",
		"resetColors": "Êtes-vous sûr de perdre toutes les couleurs actuellement définies?",
		"progress": "Tentative de résolution %% de %%",

		"colorSegments": "Couleur<br />Segments",
		"totalVials": "Total<br />Flacons",
		"emptyVials": "Vides<br />Flacons",

		"modalTitle": "ATTENDEZ!",
		"modalText": "Êtes-vous sûr de vouloir terminer cette action?",
		"yesButton": "Oui",
		"cancel": "Annuler",
		"continueButton": "Continuer",
		"sorry": "DÉSOLÉ",
		"error": "ERREUR",
		"about": "À PROPOS",
		"howToUse": "COMMENT UTILISER",
		"hotToUseTxt": "Cet outil analysera votre progression dans les jeux de style tri d'eau et tentera de vous donner une solution étape par étape, il y a 3 étapes:",
		"config": "CONFIGURATION",
		"configTxt": "Définissez les fioles équivalentes à ce qui apparaît dans votre jeu : sélectionnez les segments pour le nombre de sections de couleur qui apparaissent dans chaque fiole, le nombre total de fioles (y compris celles vides) et enfin le nombre de fioles vides.",
		"colorsTxt": "Cliquez sur chaque segment et une fenêtre contextuelle apparaîtra pour choisir une couleur pour ce segment. Si vous sélectionnez la mauvaise couleur, vous pouvez la resélectionner ou supprimer la couleur.",
		"solutionTxt": "Si vous ne connaissez pas toutes les couleurs, il tentera de résoudre le problème pour vous<sup><strong>&dagger;</strong></sup>, gardez à l'esprit qu'il ne s'agit que d'une supposition et non d'une solution garantie. Si vous connaissez toutes les couleurs et qu'il existe une solution valable, elle présentera une solution que vous pourrez parcourir d'avant en arrière pour résoudre le puzzle (si vous utilisez un ordinateur, vous pouvez également utiliser la flèche gauche/droite). clés).",
		"footnoteTxt": "<strong>&dagger;</strong> <em>étant donné que le traitement est effectué sur votre appareil, il ne tentera de résoudre que 7 couleurs inconnues ou moins.<br />Pour référence, le calcul des mouvements de chaque solution pour 7 couleurs inconnues nécessite environ 277 200 mouvements pour voir s'il existe une solution, ce qui a pris environ 5 minutes à mon ordinateur. À l'avenir, j'aimerais optimiser mon code et le projet et je revisiterai le maximum de tentatives en fonction de l'optimisation.</em>",
		//"cookies": "COOKIES",
		"cookieTxt": "Le seul cookie utilisé est Google Analytics pour surveiller l'utilisation et les échecs dans mon code. Je ne collecte aucune donnée personnelle et, comme vous pouvez le constater, il n'y a pas de publicité. <a href=\"https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage\" target=\"_new\">LocalStorage</a> est utilisé pour stocker votre préférence de langue et votre consentement à cet avis afin qu'il ne s'ouvre pas à chaque fois que vous accédez à la page.",
		"attrib": "DROITS D'AUTEUR DE CONTENU/CODE",
		"attribTxt": "<ul><li>Ruslan Kurdyumov - pour son point de départ de base <a href=\"https://github.com/rkurdyumov/water_sort_solver\" target=\"_new\">water_sort_solver</a></li><li>Michael P. Cohen - pour les <a href=\"https://www.freakflagsprite.com/\" target=\"_new\">images</a> utilisées dans la sélection de la langue.</li><li><a href=\"https://fontawesome.com/\" target=\"_new\">FontAwesome</a> - pour les icônes utilisées dans cette page</li></ul>",
		"acceptButton": "Accepter et fermer",

		"restoreProgress": "Il semble que vous ayez fait une tentative précédente, souhaitez-vous la restaurer?",

		"colors": "COULEURS",
		"reset": "RÉINITIALISER",
		"attempt": "TENTATIVE",
		"solution": "SOLUTION",
		"back": "ARRIÈRE",
		"next": "SUIVANT"
	},
	"ru-RU": {
		"noVialsSet": "Мне нужно знать, сколько там флаконов.",
		"moreEmptyVials": "Пустых флаконов не может быть столько же или больше, сколько и флаконов.",
		"noMemory": "У меня закончилась память в поисках решения, найдите больше цветов и попробуйте еще раз.",
		"noSolution": "Решение не найдено, проверьте цвета и повторите попытку.",
		"tooManySolutions": "Слишком много возможных решений, я, вероятно, заморозлю ваше устройство, пытаясь найти решение.",
		"drStrange": "Существует %% возможных решений, и обработка для их определения выполняется на вашем устройстве. Ваше устройство может перестать отвечать на запросы на некоторое время или даже зависнуть, что потребует его перезапуска.%%Насколько мне известно, вашему устройству не может быть нанесено никакого вредного постоянного ущерба.%%Вы хотите продолжить?",
		"resetColors": "Вы уверены, что все добавленные вами цвета потеряются?",
		"progress": "Попытка решения %% из ##",

		"colorSegments": "Цветные<br />сегменты",
		"totalVials": "Всего<br />Флаконов",
		"emptyVials": "Пустые<br />флаконы",

		"modalTitle": "ЖДАТЬ!",
		"modalText": "Вы уверены, что хотите завершить это действие?",
		"yesButton": "Да",
		"cancel": "Отмена",
		"continueButton": "Продолжать",
		"sorry": "ИЗВИНИ",
		"error": "ОШИБКА",
		"about": "О",
		"howToUse": "КАК ИСПОЛЬЗОВАТЬ",
		"hotToUseTxt": "Этот инструмент проанализирует ваш прогресс в играх в стиле водной сортировки и попытается дать вам пошаговое решение. Всего 3 шага:",
		"config": "КОНФИГУРАЦИЯ",
		"configTxt": "Установите флаконы, эквивалентные тем, что появляются в вашей игре: выберите сегменты для того, сколько цветных секций появляется в каждом флаконе, общее количество флаконов (включая пустые) и, наконец, количество пустых флаконов.",
		"colorsTxt": "Нажмите на каждый сегмент, и появится всплывающее окно для выбора цвета для этого сегмента. Если вы выбрали неправильный цвет, вы можете выбрать его повторно или удалить цвет.",
		"solutionTxt": "Если вы не знаете все цвета, он попытается решить ее за вас<sup><strong>&dagger;</strong></sup>, имейте в виду, что это только предположение, а не гарантированное решение. Если вы знаете все цвета и есть допустимое решение, он представит решение, по которому вы можете шагать вперед и назад, чтобы следовать за решением головоломки (если вы используете компьютер, вы также можете использовать клавиши со стрелками влево/вправо).",
		"footnoteTxt": "<strong>&dagger;</strong> <em>поскольку обработка выполняется на вашем устройстве, оно попытается решить только 7 неизвестных цветов или меньше.<br />Для справки: расчет наборов ходов каждого решения для 7 неизвестных цветов имеет около 277 200 ходов, чтобы увидеть, есть ли решение, это заняло у моего компьютера около 5 минут. В будущем я хотел бы оптимизировать свой код и проект, и я пересмотрю максимальное количество попыток в зависимости от оптимизации.</em>",
		//"cookies": "COOKIES",
		"cookieTxt": "Единственный используемый файл cookie — это Google Analytics для мониторинга использования и сбоев в моем коде. Я не собираю никаких персональных данных, и, как вы видите, нет рекламы. <a href=\"https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage\" target=\"_new\">LocalStorage</a> используется для хранения ваших языковых предпочтений и вашего согласия с этим уведомлением, чтобы оно не открывалось каждый раз, когда вы заходите на страницу.",
		"attrib": "СОДЕРЖИМОЕ/КОД АВТОРСКИЕ ПРАВА",
		"attribTxt": "<ul><li>Ruslan Kurdyumov - за его базовую отправную точку <a href=\"https://github.com/rkurdyumov/water_sort_solver\" target=\"_new\">water_sort_solver</a></li><li>Michael P. Cohen - за <a href=\"https://www.freakflagsprite.com/\" target=\"_new\">изображения</a>, используемые при выборе языка.</li><li><a href=\"https://fontawesome.com/\" target=\"_new\">FontAwesome</a> - за значки, используемые на этой странице</li></ul>",
		"acceptButton": "Принять и закрыть",

		"restoreProgress": "Похоже, вы предприняли предыдущую попытку. Хотите восстановить ее?",

		"colors": "ЦВЕТА",
		"reset": "СБРОС",
		"attempt": "ПОПЫТКА",
		"solution": "РЕШЕНИЕ",
		"back": "НАЗАД",
		"next": "СЛЕДУЮЩИЙ"
	}
}
function getString(key, replacements=[]) {
	let string = '';
	if (!strings.hasOwnProperty(lang) || !strings[lang].hasOwnProperty(key)) { string = strings['en-US'][key]; }
	else { string = strings[lang][key]; }

	for (let i=0; i < replacements.length; i++) {
		string = string.replace('%%', replacements[i]);
	}
	return string;
}